### ISSUE TITLE
I cannot for the life of me make Duke 3D function with GUS

### ISSUE THREAD

**Issue by Goi-Yaas-Dinn** [alunbestor/Boxer#62]
Using what I am quite sure is a completely stock GOG version of Duke3D Atomic I cannot play with with Boxer's preconfigured GUS. I launch the standard BUILD3D setup exe, choose Gravis Ultrasound for both the SFX and Music cards (though I try for max settings on voices and mix rate, it should be noted), and then quit the setup program and launch Duke3D through the very menu option for that choice. All is well (a bit on the tinny side; better than Apple's buggy General MIDI in El Cap though). Unfortunately, on every subsequent launch I don't even get to the title screen; the second the first few notes of "Grab-Bag" play all audio abruptly cuts out and Duke 3D freezes hard (boxer keeps on ticking, though).

Any idea why this occurs? Blood works just fine with GUS, and I'm not playing with Apple's bug-riddled MIDI shite they've had 4 different releases to fix.

**Comment by Goi-Yaas-Dinn** [comment]
It's dead, Jim.

**Comment by alunbestor** [comment]
It seems GOG no longer sell Duke Nukem 3D (presumably some rights-related fallout from Duke Nukem Forever) so their version of the game is unavailable for testing.

However, GUS sound appears to work fine in DN3D under regular Boxer 1.4.0 and development builds. It is possible that GOG had disabled GUS support or provided incorrect GUS settings in the version they were selling. (The distribution of GUS patches is on dubious legal ground, so it's possible that GOG had omitted necessary GUS files for legal reasons.)

Instead you could run your GOG copy of the game under regular Boxer, which has full GUS support. To do so:
1. Right-click on the GOG game app in Finder and choose "Show Package Contents".
2. Browse to `Contents/Resources/` and copy the "Duke Nukem 3D.boxer" file from inside it to the Desktop (or somewhere else.) This is the Boxer gamebox containing the actual game.
3. Right-click on the copy and choose "Show Package Contents" again.
4. Delete the "DOSBox Preferences.conf" file inside the gamebox. This will ensure that Boxer uses default settings for the game.
5. Double-click on the gamebox copy to launch it in standard Boxer, and then re-run SETUP.EXE to reconfigure the audio settings.

<hr>

The above instructions can be applied to any GOG game that you wish to try out in regular Boxer to see if that solves a technical problem. If the problem persists in standard Boxer, then it is within the scope of Boxer's issue tracker.

The point being: **I do not provide technical support for GOG game apps.** That is the responsibility of GOG's technical support team and their support forums.


I also do not get paid for providing technical support for Boxer, and I work a day job, so do not be surprised if questions take a while to answer; or are not answered at all, in cases where I or others are not able to test a particular game.

**Comment by Goi-Yaas-Dinn** [comment]
Where did I say the game was running in a Boxer Bundler app? It isn't. I simply Downloaded a GOG Windows installer, extracted all necessary game files, and imported them into normal Boxer. Where the GUS support is _not_ working (did you catch the part where I said it works fine initially, but not on subsequent launches?).

Had you asked, I would have gladly clarified any of these issues.

**Comment by alunbestor** [comment]
You said you were using the stock GOG version of Duke3D Atomic, so I assumed you meant the standalone bundler-based release that GOG had been selling for Mac from 2012 until the end of 2015. ([At which point, it seems, their distribution rights expired](https://www.gog.com/news/weekly_staff_picks_farewell_for_now_duke).) I realise now from the circumstances and from your wording that you probably downloaded your copy of GOG's PC release from somewhere else.

I prepared the bundled Mac version of DN3D for GOG as part of their initial Mac lineup launch, and so that was the version I grabbed for testing yesterday, although that may not be the same version of the game that's in the version you downloaded. This version had GUS disabled in its config file (because at that point we'd decided not to include GUS patches in bundles), but after reenabling it and reconfiguring the sound settings, GUS seemed to work flawlessly across several game restarts. I was not able to replicate the crash.

The PC release of the game was prepared by someone else at GOG so it may be using different settings that are causing it to crash. It would have had its own dosbox config file, which Boxer would have imported into DOSBox Preferences.conf during the import process. You should check in there to make sure there are no soundcard or CPU settings that could be interfering - the game should work correctly in Boxer with no custom configuration at all.

Failing that, I don't have any other suggestions as to why your copy isn't working, as the PC release is no longer legally available and I am unable to replicate the crash with my own version of the game.

**Comment by Goi-Yaas-Dinn** [comment]
You know what? I owe you an apology I think. Would you believe it was something as simple as Duke3D not being at the root of the drive? By the by, I have preset data for you vis a vis the BUILD3D games. Shall I list it, or is the project actually dead? I would not blame you for abandoning it, the way OS X has been headed.... :(

**Comment by alunbestor** [comment]
Duke3D doesn't normally have to live in the root of the drive, but it's likely that the GOG version was set up to expect to be in the root and Boxer imported it to the wrong place. Curious that the only thing that broke was the GUS support, but good to know for future users.

What preset data did you want to provide? I am not actively working on Boxer at the moment, but the project is not dead by any means.

**Comment by Goi-Yaas-Dinn** [comment]
>What preset data did you want to provide? I am not actively working on Boxer at the moment, but the project is not dead by any means.

I think someone is not dealing with reality...

I tell you what: I will be happy to provide preset data for you when this project shows a pulse again (or you man up and decide to let your end-users know it is no longer maintained).

**Comment by robotoad** [comment]
@Goi-Yaas-Dinn Just because commits to a volunteer project don't happen at a pace you'd like doesn't mean it's dead or that you have leverage to issue ultimatums.

**Comment by Goi-Yaas-Dinn** [comment]
@robotoad At this point there is no "pace", never mind one I'd like. And what does it being a volunteer project have to do with anything? Besides any of that, I really don't think you of all people have any room to comment: your project is notorious for treating its end-users like shit and failing to muzzle its borderline mental lead developer.

**Comment by alunbestor** [comment]
Wow. Take your grievances and your attitude elsewhere.
