### ISSUE TITLE
TheDraw does not display properly

### ISSUE THREAD

**Issue by granitepenguin** [alunbestor/Boxer#65]
Sorry, not quite sure what else to call this.  It looks like some kind of ANSI.SYS weirdness, but running The Draw in stock DOSBox 0.74 displays as expected, while it does not look quite right in Boxer

Stock:
![screen shot 2016-12-23 at 17 17 46](https://cloud.githubusercontent.com/assets/913430/21463764/e2304964-c933-11e6-8299-b9e2a51dc4a7.png)

Boxer:
![screen shot 2016-12-23 at 17 18 24](https://cloud.githubusercontent.com/assets/913430/21463767/e883b878-c933-11e6-8e5d-d57cf151a647.png)

Any ideas what settings to tweak to fix the Boxer display?

**Comment by alunbestor** [comment]
Hi Carl,
The problem here is that Boxer uses a different character set than DOSBox by default: it chooses one based on your current OSX keyboard layout. This can cause odd character choices in text-mode games.

You can force Boxer to use the DOSBox-default character set by doing the following:

1. Right-click on the game in Finder and choose “Show package contents”
2. Double-click the `DOSBox Preferences.conf` file to open it in TextEdit
3. Paste the following lines at the top of the file:
```
[dos]
keyboardlayout=none
```

Merry Christmas!

**Comment by granitepenguin** [comment]
Worked great, thanks!

Merry Christmas to you, too. :-)
